server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate     /etc/nginx/ssl/timerz.crt;
    ssl_certificate_key /etc/nginx/ssl/timerz.key;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
